[project]
name = "fonaitique"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eng-to-ipa>=0.0.2",
    "pysrt>=1.1.2",
    "tqdm>=4.67.3",
]
